name: Scheduled Ping on Todo 4

on:
  schedule:
    - cron: '*/13 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Todo app 5
        uses: srt32/uptime@v0.2
        with:
            url-to-hit: "https://todo-app-vemn.onrender.com"
            expected-statuses: "200,301"
