name: Scheduled Ping on Todo 2

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Todo app
        uses: srt32/uptime@v0.2
        with:
          expected-statuses: 200
        env:
          URL: https://todo-app-vemn.onrender.com
          METHOD: GET
